### ISSUE TITLE
Users should need to only type battery number when registering new batteries

### ISSUE THREAD

**Issue by katzuv** [DavidMasin/Battery-Logger-5987#3]
Inserting the whole code should still be supported, but the current year and the team from the settings can be used.

**Comment by DavidMasin** [comment]
Even not that, they just need to tap "Add Battery", because I know the year by time.time() and I know what should be the next number of battery with this year and team number

**Comment by katzuv** [comment]
Yep. Just make sure it's still possible to insert "custom" codes.
Note that the `datetime` module is better for getting the current year.
